version: '3.3'
services:
  decadevs_docker_michael:
    container_name: decadevs-docker-michael
    image: decadevs-docker-michael
    build: ./
    ports:
      - "8046:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: michael
      MYSQL_DATABASE: demo_db
      MYSQL_PASSWORD: password